version: "3.9"

services:

  # =========================
  # POSTGRES
  # =========================
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: mqtt_db
      POSTGRES_USER: mqtt_user
      POSTGRES_PASSWORD: mqtt_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mqtt_user -d mqtt_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  # =========================
  # REDIS
  # =========================
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  # =========================
  # MQTT BROKER
  # =========================
  mqtt:
    build:
      context: .
      dockerfile: docker/mqtt/Dockerfile
    container_name: mqtt
    ports:
      - "1883:1883"

  # =========================
  # DJANGO API
  # =========================
  api:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: api
    command: ["sh", "/app/docker/entrypoints/web.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # =========================
  # MQTT WORKER
  # =========================
  mqtt-worker:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: mqtt-worker
    command: ["sh", "/app/docker/entrypoints/mqtt.sh"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      mqtt:
        condition: service_started
      redis:
        condition: service_healthy

  # =========================
  # CELERY WORKER
  # =========================
  celery-worker:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: celery-worker
    command: ["sh", "/app/docker/entrypoints/worker.sh"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  # =========================
  # CELERY BEAT
  # =========================
  celery-beat:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: celery-beat
    command: ["sh", "/app/docker/entrypoints/beat.sh"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy

volumes:
  postgres_data: